---

- name: Update Debian based machine
  include_tasks: debian.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Update Redhat based machine
  include_tasks: redhat.yml
  when: ansible_facts['os_family'] == "RedHat"

- name: Update Windows based machine
  include_tasks: windows.yml
  when: ansible_facts['os_family'] == "Windows"